name: Cypress E2E Tests - Multi Env

on:
  workflow_dispatch:
    inputs:
      ambiente:
        description: 'Ambiente para executar os testes'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - hmg
          - prod

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests (${{ github.event.inputs.ambiente }})
        run: |
          npx cypress run --config-file=config/cypress.config.${{ github.event.inputs.ambiente }}.js
